spring:
  config:
    activate:
      on-profile: dev
  ##############################
  ###### LIQUIBASE SETTINGS #####
  ##############################
  liquibase:
    enabled: true
    contexts: development
    drop-first: false
    clear-checksums: false
    change-log: classpath:db/db.changelog-master.xml

##############################
###### DATABASE SETTINGS #####
##############################
  datasource:
    url: jdbc:postgresql://${SERVER_URI}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

##############################
######## JPA SETTINGS ########
##############################
  jpa:
    show-sql: true
    defer-datasource-initialization: true

    hibernate:
#       create | create-drop | update | validate | none>
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}

